services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"   # el nginx principal de luna-lancuba.dev hace proxy a este puerto
    depends_on:
      - almorz-api
    restart: unless-stopped

  almorz-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8081:3001"   # el nginx externo hace proxy a este puerto
    volumes:
      - ./:/srv/almorz           # mount directory (not file) to allow json-server atomic writes
    restart: unless-stopped
